### ISSUE TITLE
node.send equivalent ?

### ISSUE THREAD

**Issue by natcl** [coderofsalvation/node-red-contrib-coffeescript#1]
In a normal function node one can use the node.send() method to send messages asynchronously, (see http://nodered.org/docs/writing-functions.html)
Is that possible with the coffeescript object ?

Thanks !

**Comment by coderofsalvation** [comment]
sure, using the _cb_ function. (its actually in the example in the README.md, see here:)

```
if msg.payload.length 
  mongo.getItems (err,items) ->
    msg.succes = true
    cb(msg)                                                  <--- asynchronous return
else return msg                                          <--- synchronous return
```

**Comment by natcl** [comment]
Hmm, I tried that but I get strange results, if I print to a debug it says "Undefined"

I tried with this code:

``` coffeescript
for f in ['One', 'Two', 'Three']
    cb(f)
return msg;
```

**Comment by coderofsalvation** [comment]
I guess its because you're not passing a message object, but a string.
Try this:

```
 for f in ['One', 'Two', 'Three']
    cb({foo: f})
```

Or ideally you want to clone messages, something like:

```
 clone = (o) -> n = {} ; n[k] = v for k,v of o ; n
 newmsg = clone msg
 newmsg.foo = f
 cb(newmsg)
```

Or...you could just use https://www.npmjs.com/package/node-red-contrib-splitter (what i do as soon as i want to process arrays, chop them up into messages etc). Like so :+1: 

```
msg.payload = ['One','Two','Three']
return msg
```

This will output 3 messages, each with a 'One', 'Two', and 'Three' respectively

**Comment by natcl** [comment]
Thanks !
passing an object works !

**Comment by natcl** [comment]
Hmm would this be valid ?  Seems more pretty:

``` coffeescript
msg.payload = []

for f in ['One', 'Two', 'Three']
    msg.payload.push(f)
    @send({payload: f})
return msg;
```

**Comment by coderofsalvation** [comment]
agreed.
Not sure if that would introduce scope issues.
I would be happy if you would send me a working PR (I could add you as an contributor).

**Comment by paulwareham** [comment]
Is cb() essentially equivalent to node.send() is as to be used interchangeably if porting code  to/from coffeescript nodes and standard function nodes?

**Comment by coderofsalvation** [comment]
i think so.
It was implemented because at that time node.send() did not exist yet.
Should be easy to support both though.
